$(function() {
	@@include('global/variables.js')

	@@include('blocks/s-menu/s-menu.js')
	@@include('blocks/aside/aside.js')
	@@include('blocks/fog/fog.js')
	@@include('blocks/gallery/gallery.js')
	@@include('blocks/tab-color/tab-color.js')
	@@include('blocks/tab-size/tab-size.js')
	@@include('blocks/tab-shorts/tab-shorts.js')
	@@include('blocks/sign/sign.js')
	@@include('blocks/prop/prop.js')
	@@include('blocks/disc/disc.js')
	@@include('blocks/select/select.js')
	@@include('blocks/item/item.js')
	@@include('blocks/num/num.js')
	@@include('blocks/slider/slider.js')
	@@include('blocks/shooting/shooting.js')
	@@include('blocks/img-popup/img-popup.js')
});